# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFvZgs1pGXSr2tlVHbhnPFapgl9k5GBd
"""

!pip install langchain langchain_openai langchain_google_genai langchain_huggingface langchain_community
!pip install google-generativeai chromadb gradio numpy scikit-learn plotly

!unzip /content/Knowledge_Base_Bank.zip

import os
import glob
import numpy as np
import gradio as gr
import plotly.graph_objects as go

from sklearn.manifold import TSNE
from langchain.document_loaders import DirectoryLoader, TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.schema import Document
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings

os.environ["GOOGLE_API_KEY"] = ""

llm = ChatGoogleGenerativeAI(model="gemini-1.5-pro-latest", temperature=0.7)

# Step 3: Load Documents from Directory
folders = glob.glob("/content/Knowledge Base Bank/*")
documents = []
text_loader_kwargs = {'encoding': 'utf-8'}

for folder in folders:
    if os.path.isdir(folder):
        doc_type = os.path.basename(folder)
        loader = DirectoryLoader(folder, glob="**/*", loader_cls=TextLoader, loader_kwargs=text_loader_kwargs)
        folder_docs = loader.load()
        for doc in folder_docs:
            doc.metadata["doc_type"] = doc_type
            documents.append(doc)

print(f" Loaded {len(documents)} documents from {len(folders)} folders!")

# Step 4: Split Documents into Chunks
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = text_splitter.split_documents(documents)

len(chunks)

doc_types = set(chunk.metadata['doc_type'] for chunk in chunks)
print(f"Document types found: {', '.join(doc_types)}")

# Step 5: Create Vector Store
DB_NAME = "/content/chroma_db"
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

if os.path.exists(DB_NAME):
    Chroma(persist_directory=DB_NAME, embedding_function=embeddings).delete_collection()

vectorstore = Chroma.from_documents(documents=chunks, embedding=embeddings, persist_directory=DB_NAME)
print(f" Vectorstore created with {vectorstore._collection.count()} documents")

collection = vectorstore._collection
sample_embedding = collection.get(limit=1, include=["embeddings"])["embeddings"][0]
dimensions = len(sample_embedding)
print(f"The vectors have {dimensions:,} dimensions")

import chromadb

client = chromadb.PersistentClient(path="/content/chroma_db")

collections = client.list_collections()

for col in collections:
    print(f"Collection Name: {col}")

collection_name = "langchain"
collection = client.get_collection(collection_name)

stored_chunks = collection.get(include=["documents", "embeddings", "metadatas"])

for i, doc in enumerate(stored_chunks["documents"]):
    print(f"Chunk {i+1}:")
    print(f"  Text: {doc}")
    print(f"  Metadata: {stored_chunks['metadatas'][i]}")
    print(f"  Vector: {stored_chunks['embeddings'][i][:5]}...")
    print("-" * 50)

# Step 6: Reduce Dimensions and Visualize Data
doc_types = [chunk.metadata['doc_type'] for chunk in chunks]
vectors = np.array(vectorstore._collection.get(include=["embeddings"])['embeddings'])

category_colors = {
    "Credit Cards": "blue", "Accounts": "green", "Online Banking": "red",
    "Payment Methods": "orange", "Loans": "purple", "Investment Options": "cyan",
    "Debit Cards": "yellow", "International Banking": "pink", "Banking Regulations": "brown"
}

colors = [category_colors.get(t, "gray") for t in doc_types]

tsne_2d = TSNE(n_components=2, random_state=42)
reduced_vectors_2d = tsne_2d.fit_transform(vectors)

fig_2d = go.Figure(data=[go.Scatter(
    x=reduced_vectors_2d[:, 0],
    y=reduced_vectors_2d[:, 1],
    mode='markers',
    marker=dict(size=5, color=colors, opacity=0.8),
    text=[f"Type: {t}" for t in doc_types],
    hoverinfo='text'
)])
fig_2d.update_layout(title='2D Chroma Vector Store Visualization', width=800, height=600)
fig_2d.show()

# Step 7: Setup Conversational AI
memory = ConversationBufferMemory(memory_key='chat_history', return_messages=True)
retriever = vectorstore.as_retriever()

conversation_chain = ConversationalRetrievalChain.from_llm(
    llm=llm, retriever=retriever, memory=memory
)

def chat(message, history):
    result = conversation_chain.invoke({"question": message})
    return result["answer"]

# Step 8: Launch Chat Interface
#gr.ChatInterface(chat, type="messages").launch(inbrowser=True)

with gr.Blocks(theme="soft") as demo:
    gr.Markdown(
        """
        <h1 style='text-align: center; color: #2c3e50;'>💬 AI Banking Assistant</h1>
        <p style='text-align: center; font-size: 16px; color: #34495e;'>
        Welcome to your AI-powered banking assistant. Ask any banking-related questions, and I'll assist you!
        </p>
        """,
        elem_id="title"
    )

    gr.ChatInterface(
        fn=chat,
        chatbot=gr.Chatbot(height=300, bubble_full_width=False),
        textbox=gr.Textbox(placeholder="Type your message here...", label="Your Question", show_label=False),
        submit_btn=gr.Button("Ask", variant="primary")
    )

demo.launch(inbrowser=True, debug=True)