# -*- coding: utf-8 -*-
"""MultiModel Chatbot with OpenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SocvZAlELQ6T7MNB0eWmJMEquoS9jkf
"""

!pip install langchain langchain_openai langchain_google_genai langchain_huggingface langchain_community
!pip install google-generativeai chromadb gradio numpy scikit-learn plotly

!pip install gTTS

!unzip /content/Knowledge_Base_Bank.zip

import os
import glob
import gradio as gr

from langchain.document_loaders import DirectoryLoader, TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.schema import Document
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.vectorstores import Chroma
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
import numpy as np
import plotly.graph_objects as go
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain
from langchain.embeddings import HuggingFaceEmbeddings
from gtts import gTTS
import tempfile

MODEL = "gpt-3.5-turbo"
db_name = "vector_db"

os.environ["OPENAI_API_KEY"] = "sk-"

# Step 3: Load Documents from Directory
folders = glob.glob("/content/Knowledge Base Bank/*")
documents = []
text_loader_kwargs = {'encoding': 'utf-8'}

for folder in folders:
    if os.path.isdir(folder):
        doc_type = os.path.basename(folder)
        loader = DirectoryLoader(folder, glob="**/*", loader_cls=TextLoader, loader_kwargs=text_loader_kwargs)
        folder_docs = loader.load()
        for doc in folder_docs:
            doc.metadata["doc_type"] = doc_type
            documents.append(doc)

print(f" Loaded {len(documents)} documents from {len(folders)} folders!")

# Step 4: Split Documents into Chunks
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = text_splitter.split_documents(documents)

len(chunks)

doc_types = set(chunk.metadata['doc_type'] for chunk in chunks)
print(f"Document types found: {', '.join(doc_types)}")

embeddings = OpenAIEmbeddings()

if os.path.exists(db_name):
    Chroma(persist_directory=db_name, embedding_function=embeddings).delete_collection()

vectorstore = Chroma.from_documents(documents=chunks, embedding=embeddings, persist_directory=db_name)
print(f"Vectorstore created with {vectorstore._collection.count()} documents")

collection = vectorstore._collection
count = collection.count()

sample_embedding = collection.get(limit=1, include=["embeddings"])["embeddings"][0]
dimensions = len(sample_embedding)
print(f"There are {count:,} vectors with {dimensions:,} dimensions in the vector store")

import chromadb

client = chromadb.PersistentClient(path="/content/vector_db")

collections = client.list_collections()

for col in collections:
    print(f"Collection Name: {col}")

collection_name = "langchain"
collection = client.get_collection(collection_name)

stored_chunks = collection.get(include=["documents", "embeddings", "metadatas"])

for i, doc in enumerate(stored_chunks["documents"]):
    print(f"Chunk {i+1}:")
    print(f"  Text: {doc}")
    print(f"  Metadata: {stored_chunks['metadatas'][i]}")
    print(f"  Vector: {stored_chunks['embeddings'][i][:5]}...")
    print("-" * 50)

# Step 6: Reduce Dimensions and Visualize Data
doc_types = [chunk.metadata['doc_type'] for chunk in chunks]
vectors = np.array(vectorstore._collection.get(include=["embeddings"])['embeddings'])

category_colors = {
    "Credit Cards": "blue", "Accounts": "green", "Online Banking": "red",
    "Payment Methods": "orange", "Loans": "purple", "Investment Options": "cyan",
    "Debit Cards": "yellow", "International Banking": "pink", "Banking Regulations": "brown"
}

colors = [category_colors.get(t, "gray") for t in doc_types]

tsne_2d = TSNE(n_components=2, random_state=42)
reduced_vectors_2d = tsne_2d.fit_transform(vectors)

fig_2d = go.Figure(data=[go.Scatter(
    x=reduced_vectors_2d[:, 0],
    y=reduced_vectors_2d[:, 1],
    mode='markers',
    marker=dict(size=5, color=colors, opacity=0.8),
    text=[f"Type: {t}" for t in doc_types],
    hoverinfo='text'
)])
fig_2d.update_layout(title='2D Chroma Vector Store Visualization', width=800, height=600)
fig_2d.show()

llm = ChatOpenAI(temperature=0.7, model_name=MODEL)

memory = ConversationBufferMemory(memory_key='chat_history', return_messages=True)

retriever = vectorstore.as_retriever(embedding_functions = embeddings)

conversation_chain = ConversationalRetrievalChain.from_llm(llm=llm, retriever=retriever, memory=memory)

import openai
import tempfile
from gtts import gTTS

import gradio as gr
import base64
import os
import time
from io import BytesIO
from PIL import Image
from openai import OpenAI
import pygame

def text_to_speech(text):
    tts = gTTS(text, lang='en')
    temp_audio = tempfile.NamedTemporaryFile(delete=False, suffix='.mp3')
    tts.save(temp_audio.name)
    return temp_audio.name

def generate_image(prompt):
    image_response = openai.images.generate(
            model="dall-e-3",
            prompt=f"{prompt}, for this create a vibrant pop-art style",
            size="1024x1024",
            n=1,
            response_format="b64_json",
        )
    image_base64 = image_response.data[0].b64_json
    image_data = base64.b64decode(image_base64)
    return Image.open(BytesIO(image_data))

def chat_with_media(question, image_gen=False, audio_gen=False):
    result = conversation_chain.invoke({"question": question})
    answer = result['answer']

    output_text = answer
    output_image = None
    output_audio = None

    if image_gen:
        output_image = generate_image(answer)

    if audio_gen:
        output_audio = text_to_speech(answer)

    return output_text, output_image, output_audio

iface = gr.Interface(
    fn=chat_with_media,
    inputs=["text", gr.Checkbox(label="Generate Image"), gr.Checkbox(label="Generate Audio")],
    outputs=["text", "image", "audio"],
    title="Multi-Modal Chatbot",
    description="Chatbot with optional image and audio responses."
)

iface.launch(debug=True)

from langchain_core.callbacks import StdOutCallbackHandler

llm = ChatOpenAI(temperature=0.7, model_name=MODEL)

memory = ConversationBufferMemory(memory_key='chat_history', return_messages=True)

retriever = vectorstore.as_retriever()

conversation_chain = ConversationalRetrievalChain.from_llm(llm=llm, retriever=retriever, memory=memory, callbacks=[StdOutCallbackHandler()])

query = "tell me about debit card"
result = conversation_chain.invoke({"question": query})
answer = result["answer"]
print("\nAnswer:", answer)